//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public Books()
        {
            this.Rents = new HashSet<Rents>();
        }
    
        public int id_book { get; set; }
        public string titulo { get; set; }
        public int id_publisher { get; set; }
        public int id_author { get; set; }
        public int id_genre { get; set; }
        public int stock { get; set; }
    
        public virtual Authors Authors { get; set; }
        public virtual ICollection<Rents> Rents { get; set; }
        public virtual Genres Genres { get; set; }
        public virtual Publishers Publishers { get; set; }
    }
}
