//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Biblioteca.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rents
    {
        public int id_rent { get; set; }
        public int id_state { get; set; }
        public int id_user { get; set; }
        public int id_book { get; set; }
        public Nullable<System.DateTime> ren_date { get; set; }
        public Nullable<System.DateTime> ret_date { get; set; }
        public Nullable<System.DateTime> res_date { get; set; }
    
        public virtual Rent_States Rent_States { get; set; }
        public virtual Users Users { get; set; }
        public virtual Books Books { get; set; }
    }
}
